// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123173305_UpdateCascadeDelete")]
    partial class UpdateCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Diet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("NutrientBalanceScore")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalCalories")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Diet", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1d1d1d1-d1d1-d1d1-d1d1-d1d1d1d1d1d1"),
                            EndDate = new DateOnly(2025, 1, 31),
                            NutrientBalanceScore = 85,
                            StartDate = new DateOnly(2025, 1, 1),
                            TotalCalories = 2100.0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d2d2d2d2-d2d2-d2d2-d2d2-d2d2d2d2d2d2"),
                            EndDate = new DateOnly(2025, 2, 28),
                            NutrientBalanceScore = 90,
                            StartDate = new DateOnly(2025, 2, 1),
                            TotalCalories = 1800.0m,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DietId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DietId");

                    b.ToTable("Meal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            DietId = new Guid("d1d1d1d1-d1d1-d1d1-d1d1-d1d1d1d1d1d1"),
                            MealDate = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MealType = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            DietId = new Guid("d1d1d1d1-d1d1-d1d1-d1d1-d1d1d1d1d1d1"),
                            MealDate = new DateTime(2025, 1, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            MealType = "Lunch"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.MealProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("QuantityGrams")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("MealId", "ProductId")
                        .IsUnique();

                    b.ToTable("MealProduct", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1c1c1c1-c1c1-c1c1-c1c1-c1c1c1c1c1c1"),
                            MealId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            ProductId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1"),
                            QuantityGrams = 150m
                        },
                        new
                        {
                            Id = new Guid("c2c2c2c2-c2c2-c2c2-c2c2-c2c2c2c2c2c2"),
                            MealId = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            ProductId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            QuantityGrams = 200m
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Nutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Nutrient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1e1e1e1-e1e1-e1e1-e1e1-e1e1e1e1e1e1"),
                            Category = "Vitamins",
                            Name = "Vitamin C",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("e2e2e2e2-e2e2-e2e2-e2e2-e2e2e2e2e2e2"),
                            Category = "Minerals",
                            Name = "Iron",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("e3e3e3e3-e3e3-e3e3-e3e3-e3e3e3e3e3e3"),
                            Category = "Minerals",
                            Name = "Calcium",
                            Unit = "mg"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CaloriesPer100G")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CarbsPer100G")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("FatPer100G")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("ProteinPer100G")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1"),
                            CaloriesPer100G = 165m,
                            CarbsPer100G = 0m,
                            Category = "Meat",
                            FatPer100G = 3.6m,
                            IsVerified = true,
                            Name = "Chicken Breast",
                            ProteinPer100G = 31m
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            CaloriesPer100G = 130m,
                            CarbsPer100G = 28m,
                            Category = "Grains",
                            FatPer100G = 1.0m,
                            IsVerified = true,
                            Name = "Brown Rice",
                            ProteinPer100G = 2.7m
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.ProductNutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AmountPer100g")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<Guid>("NutrientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NutrientId");

                    b.HasIndex("ProductId", "NutrientId")
                        .IsUnique();

                    b.ToTable("ProductNutrient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1f1f1f1-f1f1-f1f1-f1f1-f1f1f1f1f1f1"),
                            AmountPer100g = 0.5m,
                            NutrientId = new Guid("e1e1e1e1-e1e1-e1e1-e1e1-e1e1e1e1e1e1"),
                            ProductId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1")
                        },
                        new
                        {
                            Id = new Guid("f2f2f2f2-f2f2-f2f2-f2f2-f2f2f2f2f2f2"),
                            AmountPer100g = 1.2m,
                            NutrientId = new Guid("e2e2e2e2-e2e2-e2e2-e2e2-e2e2e2e2e2e2"),
                            ProductId = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1")
                        },
                        new
                        {
                            Id = new Guid("f3f3f3f3-f3f3-f3f3-f3f3-f3f3f3f3f3f3"),
                            AmountPer100g = 10.0m,
                            NutrientId = new Guid("e3e3e3e3-e3e3-e3e3-e3e3-e3e3e3e3e3e3"),
                            ProductId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2")
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DietaryRestrictions")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ActivityLevel = "Moderate",
                            BirthDate = new DateOnly(1990, 1, 1),
                            CreatedAt = new DateTime(2025, 11, 23, 17, 33, 3, 267, DateTimeKind.Utc).AddTicks(8481),
                            Email = "admin@example.com",
                            Gender = "Male",
                            GoalType = "WeightLoss",
                            Height = 180.0m,
                            PasswordHash = "hashed_password_1",
                            Weight = 80.5m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ActivityLevel = "Active",
                            BirthDate = new DateOnly(1995, 5, 15),
                            CreatedAt = new DateTime(2025, 11, 23, 17, 33, 3, 267, DateTimeKind.Utc).AddTicks(8485),
                            DietaryRestrictions = "Vegetarian",
                            Email = "user@example.com",
                            Gender = "Female",
                            GoalType = "MuscleGain",
                            Height = 165.0m,
                            PasswordHash = "hashed_password_2",
                            Weight = 60.0m
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Diet", b =>
                {
                    b.HasOne("WebApplication1.Models.User", "User")
                        .WithMany("Diets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.Meal", b =>
                {
                    b.HasOne("WebApplication1.Models.Diet", "Diet")
                        .WithMany("Meals")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");
                });

            modelBuilder.Entity("WebApplication1.Models.MealProduct", b =>
                {
                    b.HasOne("WebApplication1.Models.Meal", "Meal")
                        .WithMany("MealProducts")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Product", "Product")
                        .WithMany("MealProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApplication1.Models.ProductNutrient", b =>
                {
                    b.HasOne("WebApplication1.Models.Nutrient", "Nutrient")
                        .WithMany("ProductNutrients")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Product", "Product")
                        .WithMany("ProductNutrients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutrient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApplication1.Models.Diet", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("WebApplication1.Models.Meal", b =>
                {
                    b.Navigation("MealProducts");
                });

            modelBuilder.Entity("WebApplication1.Models.Nutrient", b =>
                {
                    b.Navigation("ProductNutrients");
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Navigation("MealProducts");

                    b.Navigation("ProductNutrients");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Navigation("Diets");
                });
#pragma warning restore 612, 618
        }
    }
}
